# Generated by Django 4.2.6 on 2023-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                ("computingTokens", models.IntegerField()),
                ("completionTokens", models.IntegerField()),
                ("totalTokens", models.IntegerField()),
            ],
        ),
    ]
