# Generated by Django 4.2.6 on 2023-10-24 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="questionmodel",
            table="questions",
        ),
    ]
