# Generated by Django 4.2.6 on 2023-10-24 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_questionmodel_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="questionmodel",
            table="question",
        ),
    ]
