version: "3.6"

services:

  back:
    tty: true
    build:
      context: ../../code/aiResume
      dockerfile: ../../ops/docker/backend/dev/Dockerfile
    volumes:
      - ../../code/aiResume:/app
    restart: on-failure

  database:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=verysecretpass
    restart: always
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=verysecretpass" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db: